version: '3.8'

services:
  #php:8.1
  app:
    build:
      args:
        user: rafael
        uid: 1000
      context: ./docker/laravel/
      dockerfile: Dockerfile
    image: rafael/laravel-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    depends_on:
      - redis
      - queue
    networks:
      - docker-laravel

  #nginx
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel

  # db
  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker-laravel

  # redis
  redis:
    image: redis:latest
    networks:
      - docker-laravel

  # queue
  queue:
    build:
      args:
        user: rafael
        uid: 1000
      context: ./docker/laravel/
      dockerfile: Dockerfile
    restart: always
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - docker-laravel

networks:
  docker-laravel:
    driver: bridge
